# Generated by Django 4.2.30 on 2026-06-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_remove_article_updated_date_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField(blank=True)),
                ('articles', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.article')),
            ],
        ),
    ]
